# Generated by Django 2.1.4 on 2018-12-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100, unique=True)),
                ('taskdesc', models.CharField(max_length=600)),
                ('inputs', models.CharField(max_length=300)),
                ('outputs', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('degree', models.IntegerField()),
                ('letter', models.CharField(max_length=3)),
                ('donetask', models.ManyToManyField(to='asp.tasks')),
            ],
        ),
    ]
