# Generated by Django 2.1.4 on 2018-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0002_auto_20181215_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Letter',
            new_name='letter',
        ),
    ]
