# Generated by Django 2.1.4 on 2019-01-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0002_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='testin',
            field=models.CharField(default='тест не найден', max_length=300),
        ),
        migrations.AddField(
            model_name='tasks',
            name='testout',
            field=models.CharField(default='тест не найден', max_length=300),
        ),
    ]
