# Generated by Django 2.1.4 on 2018-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0003_auto_20181216_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
