# Generated by Django 2.1.4 on 2018-12-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0004_auto_20181219_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='letter',
            field=models.CharField(max_length=3),
        ),
    ]
