# Generated by Django 2.1.5 on 2019-01-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0004_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='donetask',
        ),
    ]
