# Generated by Django 2.1.5 on 2019-01-20 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0005_remove_users_donetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 3, 16, 7, 847692)),
        ),
    ]
