# Generated by Django 2.1.4 on 2018-12-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0005_auto_20181219_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100, unique=True)),
                ('taskdesc', models.CharField(max_length=600)),
                ('inputs', models.CharField(max_length=300)),
                ('outputs', models.CharField(max_length=300)),
            ],
        ),
    ]
