# Generated by Django 2.1.5 on 2019-01-20 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0006_auto_20190120_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 3, 21, 39, 670187)),
        ),
    ]
