# Generated by Django 2.1.5 on 2019-01-20 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0007_auto_20190120_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 3, 38, 32, 39855)),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ManyToManyField(to='asp.Users'),
        ),
    ]
