# Generated by Django 2.1.5 on 2019-01-20 00:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0008_auto_20190120_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 3, 45, 11, 410026)),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asp.Users'),
        ),
    ]
