# Generated by Django 2.1.5 on 2019-01-24 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0009_auto_20190120_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 22, 36, 1, 36053)),
        ),
    ]
