# Generated by Django 2.1.5 on 2019-01-25 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0010_auto_20190124_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 22, 32, 31, 579922)),
        ),
    ]
