# Generated by Django 2.1.5 on 2019-01-25 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0011_auto_20190125_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='lang',
            field=models.CharField(default='Python 3.7.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 23, 35, 34, 630769)),
        ),
    ]
