# Generated by Django 2.1.5 on 2019-01-27 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0012_auto_20190125_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='tests',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 4, 20, 47, 906752)),
        ),
    ]
