# Generated by Django 2.1.5 on 2019-02-16 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0015_auto_20190216_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 20, 17, 1, 852667)),
        ),
    ]
