# Generated by Django 2.1.5 on 2019-02-16 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0017_auto_20190217_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 1, 15, 10, 24548)),
        ),
    ]
