# Generated by Django 2.1.5 on 2019-02-17 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0018_auto_20190217_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='tests',
            field=models.CharField(default='0', max_length=2500),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 21, 59, 1, 387504)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='inputs',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='outputs',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskdesc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='testin',
            field=models.CharField(default='тест не найден', max_length=1200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='testout',
            field=models.CharField(default='тест не найден', max_length=1200),
        ),
        migrations.AlterField(
            model_name='users',
            name='letter',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
