# Generated by Django 2.1.5 on 2019-02-18 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0019_auto_20190217_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 14, 5, 48, 299868)),
        ),
    ]
