# Generated by Django 2.1.5 on 2019-02-19 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0020_auto_20190218_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('needCompilation', models.BooleanField()),
                ('version', models.CharField(max_length=20)),
                ('path', models.FilePathField()),
                ('compilationParams', models.CharField(default=None, max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 2, 15, 4, 901733)),
        ),
    ]
