# Generated by Django 2.1.5 on 2019-02-19 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0021_auto_20190220_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiler',
            name='version',
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 2, 17, 34, 217853)),
        ),
    ]
