# Generated by Django 2.1.5 on 2019-02-20 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0023_auto_20190220_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 3, 0, 57, 197766)),
        ),
    ]
