# Generated by Django 2.1.5 on 2019-02-20 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0024_auto_20190220_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='params',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 13, 27, 45, 372610)),
        ),
    ]
