# Generated by Django 2.1.5 on 2019-02-20 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0025_auto_20190220_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='params',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 13, 28, 20, 478691)),
        ),
    ]
