# Generated by Django 2.1.5 on 2019-02-20 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0026_auto_20190220_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='extention',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 13, 42, 22, 576362)),
        ),
    ]
