# Generated by Django 2.1.5 on 2020-04-23 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0027_auto_20190220_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 18, 13, 36, 563448)),
        ),
    ]
